name: Build dev container on lab

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/build-and-push-lab.yml'
  workflow_dispatch:

env:
    REGISTRY: "harbor.harbor"

jobs:
  build:
    runs-on: lab
    container:
        image: gcr.io/kaniko-project/executor:v1.23.2-debug # the kaniko image
    permissions:
        contents: read # read the repository

    steps:
        - name: Build and Push Image to ACR with kaniko
          run: |
            echo "{  \"auths\": { \"http://${{ env.REGISTRY }}\": { \"auth\": \"${{ secrets.HARBOR_AUTH }}\"  }  } }" > /kaniko/.docker/config.json

            /kaniko/executor \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
            --context-sub-path="crm" \
            --dockerfile="./Dockerfile" \
            --destination=${{ env.REGISTRY }}/otel/dev-container:${TAG} \
            --destination=${{ env.REGISTRY }}/otel/dev-container:latest \
            --insecure-registry ${{ env.REGISTRY }} \
            --cache=true \
            --cache-run-layers=true \
            --cache-copy-layers=true \
            --cache-dir="${KANIKO_DIR}/cache" \
            --cache-ttl=24h \
            --compressed-caching=false \
            --single-snapshot \
            --cleanup \
            --use-new-run \
            --push-retry 5
          env:
            GIT_USERNAME: ${{ github.actor }}
            GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  
